BenimKutuphane/Controllers/PanelimController.cs
using BenimKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BenimKutuphane.Controllers
{
    public class PanelimController : Controller
    {
        // GET: Panelim
        DBKUTUPHANEEntities1 db = new DBKUTUPHANEEntities1();
        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var uyemail = (string)Session["Mail"];
            var degerler = db.TabloUyeler.FirstOrDefault(z => z.Mail == uyemail);
            return View(degerler);
        }
        [HttpPost]
        public ActionResult Index2(TabloUyeler p)
        {
            var kullanici = (string)Session["Mail"];
            var uye = db.TabloUyeler.FirstOrDefault(x => x.Mail == kullanici);
            uye.Sifre = p.Sifre;
            uye.Ad = p.Ad;
            uye.Soyad = p.Soyad;
            uye.KullaniciAdi = p.KullaniciAdi;
            uye.Fotograf = p.Fotograf;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Kitaplarim()
        {
            var kullanici = (string)Session["Mail"];
            var id = db.TabloUyeler.Where(x=>x.Mail==kullanici.ToString()).Select(z=>z.ID).FirstOrDefault();
            var degerler = db.TabloHareket.Where(x => x.Uye == id).ToList();
            return View(degerler);
        }
        public ActionResult LogOut() 
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("GirisYap", "Login");     
        }
    }
}

BenimKutuphane/Views/Panelim/Index.cshtml
@model BenimKutuphane.Models.Entity.TabloUyeler
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}

<h2>Kullanıcı Bilgilerim</h2>


@using (Html.BeginForm("Index2", "Panelim", FormMethod.Post))
{
    <table class="table table-hover" style="margin-top:25px">
        <tr>
            <td>
                @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                <label style="font-weight:bold">Mail Adresi : </label> @HttpContext.Current.User.Identity.Name
            </td>
        </tr>
        <tr>
            <td>
                @Html.TextBoxFor(x => x.KullaniciAdi, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.TextBoxFor(x => x.Sifre, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.TextBoxFor(x => x.Fotograf, new { @class = "form-control" })
            </td>
        </tr>
        <tr>
            <td>
                <button class="btn btn-warning">Bilgilerimi Güncelle</button>
            </td>
        </tr>
    </table>
}

BenimKutuphane/Views/Panelim/Kitaplarim.cshtml
@using BenimKutuphane.Models.Entity
@model List<TabloHareket>
@{
    ViewBag.Title = "Kitaplarim";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}
<br />
<h2>Geçmiş Kitaplarım</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Kitap Adı</th>
        <th>Aldığım Tarih</th>
        <th>İade Tarihim</th>
    </tr>
    @foreach (var k in Model)
        {
            <tr>
                <td>@k.TabloKitap.Ad</td>
                <td>@Convert.ToDateTime(k.AlisTarihi).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(k.GetirdigiTarih).ToString("dd/MM/yyyy")</td>
            </tr>
        }
</table>