BenimKutuphane/Controllers/OduncKitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using BenimKutuphane.Models.Entity;

namespace BenimKutuphane.Controllers
{
    public class OduncKitapController : Controller
    {
        // GET: OduncKitap
        DBKUTUPHANEEntities1 db = new DBKUTUPHANEEntities1();
        public ActionResult Index()
        {
            var degerler = db.TabloHareket.Where(x => x.IslemDurum == false).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult OduncVer()
        {
            List<SelectListItem> deger1 = (from x in db.TabloUyeler.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Ad + " " + x.Soyad,
                                               Value = x.ID.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in db.TabloKitap.Where(x=>x.KitapDurum==true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Ad,
                                               Value = x.ID.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in db.TabloPersonel.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAdSoyad,
                                               Value = x.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult OduncVer(TabloHareket p)
        {
            var d1 = db.TabloUyeler.Where(x => x.ID == p.TabloUyeler.ID).FirstOrDefault();
            var d2 = db.TabloKitap.Where(y => y.ID == p.TabloKitap.ID).FirstOrDefault();
            var d3 = db.TabloPersonel.Where(z => z.ID == p.TabloPersonel.ID).FirstOrDefault();
            p.TabloUyeler = d1;
            p.TabloKitap = d2;
            p.TabloPersonel = d3;
            db.TabloHareket.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult OduncIade(TabloHareket p)
        {
            var odnc = db.TabloHareket.Find(p.ID);
            DateTime d1 = DateTime.Parse(odnc.IadeTarih.ToString());
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;
            ViewBag.dgr = d3.TotalDays;
            return View("OduncIade", odnc);
        }
        public ActionResult OduncKitapGuncelle(TabloHareket p)
        {
            var odnc = db.TabloHareket.Find(p.ID);
            odnc.GetirdigiTarih = p.GetirdigiTarih;
            odnc.IslemDurum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BenimKutuphane/Views/OduncKitap/Index.cshtml
@using BenimKutuphane.Models.Entity
@model List<TabloHareket>
    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/Layout.cshtml";
    }

    <h2 style="margin-top:15px">Ödünç Kitap Listesi</h2>

    <table class="table table-bordered">
        <tr>
            <th>İşlem ID</th>
            <th>Kitap Adı</th>
            <th>Üye</th>
            <th>Personel</th>
            <th>Alış Tarihi</th>
            <th>İade Tarihi</th>
           @* <th>İade Et</th>*@
        </tr>
        @foreach (var k in Model)
        {
            <tr>
                <td>@k.ID</td>
                <td>@k.TabloKitap.Ad</td>
                <td>@k.TabloUyeler.Ad&nbsp @k.TabloUyeler.Soyad</td>
                <td>@k.TabloPersonel.PersonelAdSoyad</td>
                <td>@Convert.ToDateTime(k.AlisTarihi).ToString("dd/MM/yyyy")</td>
                <td>@Convert.ToDateTime(k.IadeTarih).ToString("dd/MM/yyyy")</td>
                <td><a href="/OduncKitap/OduncIade/@k.ID" class="btn btn-danger">İade Et</a></td>
            </tr>
        }
    </table>

BenimKutuphane/Views/OduncKitap/OduncIade.cshtml
@model BenimKutuphane.Models.Entity.TabloHareket
@{
    ViewBag.Title = "OduncIade";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("OduncKitapGuncelle", "OduncKitap", FormMethod.Post))
{
    <div style="margin-top:15px"></div>
    <div class="form-group">
        <label>Hareker ID</label>
        @Html.LabelFor(p => p.ID)
        @Html.TextBoxFor(p => p.ID, new { @class = "form-control" })
        <br />
        <label>Kitap Adı</label>
        @Html.TextBoxFor(p => p.TabloKitap.Ad, new { @class = "form-control" })
        <br />
        <label>Kitabı Alan Üye</label>
        @Html.TextBoxFor(p => p.TabloUyeler.Ad, new { @class = "form-control" })
        <br />
        <label>Kitabı Veren Personel</label>
        @Html.TextBoxFor(p => p.TabloPersonel.PersonelAdSoyad, new { @class = "form-control" })
        <br />
        <label>Kitabın Alış Tarihi</label>
        @Html.TextBoxFor(p => p.AlisTarihi, "{0: dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Kitabın İade Edilmesi Gereken Tarih</label>
        @Html.TextBoxFor(p => p.IadeTarih, "{0: dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Kitabın İade Edildiği Tarih</label>
        <input type="text" class="form-control" name="GetirdigiTarih"
               value="@DateTime.Now.ToShortDateString()" />
        <br />
        <label>Geç Gelen Gün Sayısı</label>
        <input type="text" class="form-control" id="GecGelenInput" value="@ViewBag.dgr" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-success">Ödünç Kitabı Geri al</button>
    </div>
}

BenimKutuphane/Views/OduncKitap/OduncVer.cshtml
@model BenimKutuphane.Models.Entity.TabloHareket
@{
    ViewBag.Title = "OduncVer";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <b>Üye</b>
        @Html.DropDownListFor(k => k.TabloUyeler.ID, (List<SelectListItem>)ViewBag.dgr1,
       new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <b>Kitap</b>
        @Html.DropDownListFor(k => k.TabloKitap.ID, (List<SelectListItem>)ViewBag.dgr2,
      new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <b>Personel</b>
        @Html.DropDownListFor(k => k.TabloPersonel.ID, (List<SelectListItem>)ViewBag.dgr3,
      new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <b>Kitap Alış Tarihi</b>
        <input type="text" class="form-control" name="AlisTarihi"
               value="@DateTime.Now.ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <b>Kitap İade Tarihi</b>
        <input type="text" class="form-control" name="IadeTarih"
               value="@DateTime.Now.AddDays(15).ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Kitabı Ödünç Ver</button>
        <input type="hidden" value="false" name="IslemDurum">
    </div>

</form>